import { Lexend_Zetta } from "next/font/google";
import "./globals.css";

const lexend = Lexend_Zetta({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lexend.variable}  antialiased`}>{children}</body>
    </html>
  );
}
